#!/bin/bash
# Get battery status.
#
# Returns:
#   The battery's status or state.
get_battery_status() {
    echo "$__UPOWER_INFO" | awk -W posix '$1 == "state:" {print $2}'
}

# Get battery percentage.
#
# Returns:
#   The battery's percentage, without the %.
get_battery_percent() {
    echo "$__UPOWER_INFO" | awk -W posix '$1 == "percentage:" { gsub("%","",$2); print $2}'
}

BATT_DEVICE=$(upower -e | grep -o 'BAT[0-9]' | head -n 1)
__UPOWER_INFO=$(upower --show-info "/org/freedesktop/UPower/devices/battery_${BLOCK_INSTANCE:-$BATT_DEVICE}")

BATT_PERCENT=$(get_battery_percent)
CHARGE_STATE=$(get_battery_status)

if [ -z "$BATT_PERCENT" ]; then
    exit 0
elif [ "$BATT_PERCENT" -ge 0 ] && [ "$BATT_PERCENT" -le 20 ]; then
    LABEL_ICON=""
    VALUE_COLOR="#d93b3b"
elif [ "$BATT_PERCENT" -ge 20 ] && [ "$BATT_PERCENT" -le 50 ]; then
    LABEL_ICON=""
    VALUE_COLOR="#f27222"
elif [ "$BATT_PERCENT" -ge 50 ] && [ "$BATT_PERCENT" -le 80 ]; then
    LABEL_ICON=""
    VALUE_COLOR="#E5E9F0"
elif [ "$BATT_PERCENT" -ge 80 ] && [ "$BATT_PERCENT" -le 98 ]; then
    LABEL_ICON=""
    VALUE_COLOR="#E5E9F0"
else
    LABEL_ICON=""
    VALUE_COLOR="#E5E9F0"
fi

if [ -z "$CHARGE_STATE" ]; then
    exit 0
elif [ "$CHARGE_STATE" == "discharging" ]; then
    CHARGE_ICON=""
elif [ "$CHARGE_STATE" == "charging" ]; then
    CHARGE_ICON=""
else
    CHARGE_ICON=""
fi

#echo "<span color=\"${LABEL_COLOR}\">$LABEL_ICON</span><span font_desc=\"${VALUE_FONT}\" color=\"${VALUE_COLOR}\"> $BATT_PERCENT%</span><span color=\"${LABEL_COLOR}\">$CHARGE_ICON</span>"

echo "$LABEL_ICON $BATT_PERCENT% $CHARGE_ICON"
echo "$LABEL_ICON $BATT_PERCENT% $CHARGE_ICON"
echo "$VALUE_COLOR"

if [ "$button" == "1" ]; then
    #/usr/bin/i3-msg -q exec /usr/bin/gnome-control-center power
    #headphone battery status
    headphone=$(/home/akss13/bin/Bluetooth_Headset_Battery_Level/bluetooth_battery.py 70:99:1C:B0:86:5A)
    strip="Battery level for 70:99:1C:B0:86:5A is "
    headphone=$(echo "${headphone#$strip}")
    #mouse battery status
    mouse_batt=$(upower --show-info "/org/freedesktop/UPower/devices/mouse_hid_34o88o5dob6oe4of5_battery")
    mouse_batt=$(echo "$mouse_batt" | awk -W posix '$1 == "percentage:" { gsub("%","",$2); print $2}')
    #send notification
    notify-send -i "battery" 'Battery status' "Laptop battery: $BATT_PERCENT%\nHeadphone battery: $headphone\nMouse battery: $mouse_batt%"
fi
