#!/usr/bin/env perl
#
use strict;
use warnings;
use utf8;
use Getopt::Long;

# default values
my $t_warn = 50;
my $t_crit = 80;
my $cpu_usage = -1;
my $decimals = $ENV{DECIMALS} // 0;
my $label = $ENV{LABEL} // "";

sub help {
    print "Usage: cpu_usage [-w <warning>] [-c <critical>] [-d <decimals>]\n";
    print "-w <percent>: warning threshold to become yellow\n";
    print "-c <percent>: critical threshold to become red\n";
    print "-d <decimals>:  Use <decimals> decimals for percentage (default is $decimals) \n"; 
    exit 0;
}

GetOptions("help|h" => \&help,
           "w=i"    => \$t_warn,
           "c=i"    => \$t_crit,
           "d=i"    => \$decimals,
);

# Get CPU usage
$ENV{LC_ALL}="en_US"; # if mpstat is not run under en_US locale, things may break, so make sure it is
open (MPSTAT, 'mpstat 1 1 |') or die;
while (<MPSTAT>) {
    if (/^.*\s+(\d+\.\d+)[\s\x00]?$/) {
        $cpu_usage = 100 - $1; # 100% - %idle
        last;
    }
}
close(MPSTAT);

$cpu_usage eq -1 and die 'Can\'t find CPU information';

#Color generation based on usage
my $font_color="#E5E9F0";
if ($cpu_usage >= $t_crit) {
$font_color="#d93b3b\n";
}elsif ($cpu_usage >= $t_warn) {
$font_color="#ebd63d\n";
}else{
$font_color="#E5E9F0\n"
}

# Print short_text, full_text
binmode(STDOUT, "encoding(UTF-8)");
printf " %.${decimals}f%%\n", $cpu_usage;
printf " %.${decimals}f%%\n", $cpu_usage;

# Print color, if needed

if ($cpu_usage >=-1){
print $font_color;
}

exit 0;
