#!/bin/bash

TEMP=$(sensors | sed -rn 's/.*Package id 0:\s+.([0-9.]+).*/\1/p')
echo $TEMP
echo $TEMP
#if [[ ${TEMP} -gt 90 ]]
#then
#    echo '<span style=color: #d93b3b;">hello world</span>'
#elif [[ ${TEMP} -gt 70 ]]
#then
#    COLOR=${warning:-$(xrescat i3xrocks.warning "#EBCB8B")}
#else
#    COLOR=${color:-$(xrescat i3xrocks.value.color "#D8DEE9")}
#fi



