#!/bin/bash
var=$(python bluetooth_data.py 2>&1)
echo "  ""<span font='FontAwesome 12'>$var</span>"

if [ ! -z "$button" ]; then
    /usr/bin/i3-msg -q exec /usr/bin/gnome-control-center bluetooth
fi
